Сделана навигация пока без логики.
Sparky-web/studentto pull request #13
Opened 2022-09-13 17:42 UTC by Binatik

Сделал компонент, navButton, который принимает 3 пропса. Компонент статический.
Сверстана страница с навигацией слева.  

Осталось сделать боковую панель с днями недели, пока не очень понимаю как.

2022-09-14 18:39 UTC, Binatik commented
Исправил проблемы описанные выше. Сверстал и подключил отрисовку данных.  Пока не знаю как получаем группу, сейчас все данные сразу в days. 

Не помещается как на макете карточки, решил попробовать сделать меню фиксом, тогда у карточки больше места и 6 дней хватает. Но при сужении экрана происходит беда.

2022-09-14 20:31 UTC, Sparky-web commented
1. Правильно, aside нужно делать через position: fixed, однако если ты так делаешь, то нужно задавать ему точную ширину, и потом на основной странице делать такой отступ слева
![image](https://user-images.githubusercontent.com/65344272/190255704-928edbb2-5cae-4c8c-b58d-6576424e15b9.png)
2. 
![image](https://user-images.githubusercontent.com/65344272/190255834-1b70dda2-4fe4-4c7d-a229-af607305ce9d.png)
Вот тут у тебя SideNavigation с position: fixed, при таком раскладе spacing на стеке не действует и стек в принципе лишний. Правильней будет убрать стек вообще, DesktopSchedule обернуть в Box, а на Box накинуть marginleft: calc(ширина боковой панели + theme.spacing(4)

2022-09-15 16:56 UTC, Binatik commented
При попытке сделать Plug, все ломается, fixed занимает 100% высоты page, ```absolute``` не нужен думаю.
В ```Box``` указан ```relative```, но это не дает результата.

Строка кода:
```const width = lessonScreenRef.current.scrollWidth;``` не дает ширину с учетом scroll```
Временно стоит частичная прокрутка ```scrollBy(100, 0)```

2022-09-18 19:56 UTC, Sparky-web requested changes

2022-09-18 19:56 UTC, Sparky-web commented on frontend/pages/students/desktop.js
> +    function dateISO(method, params, key) {
1. Метод dateISO - должен сдвигать диапазон времени вперед или назад. Логичней его назвать moveRange.
2. DateTime.now() не принимает в себя никакие аргументы (range[0] и [1] игнорируются), скорее всего тебе нужен метод DateTime.fromISO: https://moment.github.io/luxon/api-docs/index.html#datetimefromiso

2022-09-18 19:56 UTC, Sparky-web commented on frontend/pages/students/desktop.js
> +                    current
Current - кнопка, которая должна сбрасывать диапазон до текущей недели, ты же пытаешься трансформировать range, для этой кнопки создай другой метод: resetRange()

2022-09-20 19:40 UTC, merged